const GEAR_BRANDS: Record<string, BrandData> = {
    '100mountain': { name: '100mountain' },
    '3fulgear': { name: '3FULGEAR' },
    '3m': { name: '3M' },
    '4t2': { name: '4T2' },
    '5050-workshop': { name: '5050 WORKSHOP' },
    'and-wonder': { name: 'and wonder' },
    'atelier-blue-bottle': { name: 'atelier Blue bottle' },
    'beast-runners': { name: 'Beast Runners' },
    'bed-rocks': { name: 'Bed Rocks' },
    'beyond-the-trailhead': { name: 'Beyond the Trailhead' },
    'big-agnes': { name: 'Big Agnes' },
    'black-diamond': { name: 'Black Diamond' },
    'brown-by-2-tacs': { name: 'BROWN by 2-tacs' },
    'burlap-outfitter': { name: 'BURLAP OUTFITTER' },
    'camping-ace': { name: 'Camping Ace' },
    'cascade-wild': { name: 'Cascade Wild' },
    'changyue-studio': { name: 'Changyue Studio' },
    'common-gear': { name: 'common gear' },
    'corner-trip': { name: 'corner trip' },
    'da-jiang': { name: 'DJI | Da-Jiang' },
    'darn-tough': { name: 'Darn Tough' },
    'durston-gear': { name: 'Durston Gear' },
    'emo-outdoors': { name: 'EMO Outdoors' },
    'f-ce': { name: 'F/CE' },
    'field-record': { name: 'FIELD RECORD' },
    'goal-zero': { name: 'Goal Zero' },
    'gossamer-gear': { name: 'Gossamer Gear' },
    'granite-gear': { name: 'Granite Gear' },
    'high-tail-designs': { name: 'High Tail Designs' },
    'hiker-club': { name: 'Hiker Club' },
    'hiker-trash': { name: 'Hiker Trash' },
    'hoka-one-one': { name: 'Hoka One One' },
    'hydro-flask': { name: 'Hydro Flask' },
    'idea-sekikawa': { name: 'Idea Sekikawa' },
    'katabatic-gear': { name: 'Katabatic Gear' },
    'keep-on': { name: 'Keep On' },
    'klean-kanteen': { name: 'Klean Kanteen' },
    'kula-cloth': { name: 'Kula Cloth' },
    'la-sportiva': { name: 'La Sportiva' },
    'led-lenser': { name: 'LED LENSER' },
    'life-sports': { name: 'Life Sports' },
    'light-my-fire': { name: 'LIGHT MY FIRE' },
    'locus-gear': { name: 'LOCUS GEAR' },
    'lowe-alpine': { name: 'Lowe Alpine' },
    'luna-sandals': { name: 'Luna Sandals' },
    'meili-isle-studio': { name: 'MEILI ISLE STUDIO' },
    'mont-bell': { name: 'Mont-bell', originalName: 'モンベル' },
    'mountain-equipment': { name: 'Mountain Equipment' },
    'mountain-hardwear': { name: 'Mountain Hardwear' },
    'move-free': { name: 'Move Free' },
    'mystery-ranch': { name: 'MYSTERY RANCH' },
    'nite-ize': { name: 'Nite Ize' },
    'no-w': { name: 'no/W' },
    'nozzle-quiz': { name: 'Nozzle quiz' },
    'or-this-way': { name: 'OR THIS WAY' },
    'outdoor-research': { name: 'Outdoor Research' },
    'owl-mils': { name: 'OWL MILS' },
    'paago-works': { name: 'PaaGo WORKS' },
    'peak-design': { name: 'Peak Design' },
    'race-on': { name: 'Race On', originalName: '銳速' },
    'royal-robbins': { name: 'Royal Robbins' },
    'sea-to-summit': { name: 'Sea to Summit' },
    'senchi-designs': { name: 'Senchi Designs' },
    'sierra-designs': { name: 'Sierra Designs' },
    'six-moon-designs': { name: 'Six Moon Designs' },
    'snow-peak': { name: 'Snow Peak', originalName: 'スノーピーク' },
    'solar-puff': { name: 'Solar Puff' },
    'solo-stove': { name: 'Solo Stove' },
    'source-tactical-gear': { name: 'SOURCE Tactical Gear' },
    'tar-p-ment': { name: 'TAR(P)MENT' },
    'teton-bros': { name: 'Teton Bros' },
    'the-north-face': { name: 'The North Face' },
    'therm-a-rest': { name: 'Therm-a-Rest' },
    'topo-athletic': { name: 'Topo Athletic' },
    'trail-bum': { name: 'Trail Bum' },
    'tread-lite-gear': { name: 'Tread Lite Gear' },
    'ula-equipment': { name: 'ULA Equipment' },
    'up-sport': { name: 'UP Sport' },
    'waymark-gear-co': { name: 'Waymark Gear Co.' },
    'western-mountaineering': { name: 'Western Mountaineering' },
    'yamatomo-fun': { name: 'YAMATOMO.FUN' },
    adidsi: { name: 'ADIDSI' },
    aigle: { name: 'AIGLE' },
    alico: { name: 'ALICO' },
    alps: { name: 'ALPS Mountaineering' },
    altra: { name: 'Altra' },
    apple: { name: 'Apple' },
    arcteryx: { name: "Arc'teryx" },
    asics: { name: 'Asics' },
    asolo: { name: 'ASOLO' },
    atunas: { name: 'Atunas' },
    axesquin: { name: 'AXESQUIN', originalName: '凌' },
    beal: { name: 'Beal' },
    belmont: { name: 'Belmont' },
    bergans: { name: 'Bergans' },
    biolite: { name: 'BioLite' },
    blackburn: { name: 'Blackburn' },
    blackyak: { name: 'BLACKYAK' },
    boglerco: { name: 'BoglerCo' },
    bonfus: { name: 'BONFUS' },
    braasi: { name: 'BRAASI' },
    brs: { name: 'BRS' },
    buff: { name: 'Buff' },
    c2h3: { name: 'C2H3' },
    c3fit: { name: 'C3fit' },
    camelbak: { name: 'CamelBak' },
    camp: { name: 'CAMP' },
    canon: { name: 'Canon' },
    caravan: { name: 'Caravan' },
    cascade: { name: 'Cascade Mountain Tech' },
    casio: { name: 'CASIO' },
    cayl: { name: 'CAYL' },
    chaco: { name: 'Chaco' },
    chaoras: { name: 'Chaoras' },
    ciele: { name: 'Ciele' },
    cnoc: { name: 'CNOC' },
    coghlans: { name: 'Coghlans' },
    coleman: { name: 'Coleman' },
    columbia: { name: 'Columbia' },
    compressport: { name: 'Compressport' },
    cotopaxi: { name: 'Cotopaxi' },
    craft: { name: 'CRAFT' },
    crystal: { name: 'Crystal' },
    ct: { name: 'climbing technology' },
    ctug: { name: 'CTUG' },
    culoclean: { name: 'CuloClean' },
    cumulus: { name: 'Cumulus' },
    decathlon: { name: 'Decathlon' },
    deuter: { name: 'Deuter' },
    dexshell: { name: 'Dexshell' },
    dinex: { name: 'Dinex' },
    dmm: { name: 'DMM' },
    edelrid: { name: 'Edelrid' },
    enforma: { name: 'Enforma' },
    enlightened: { name: 'Enlightened Equipment' },
    epigas: { name: 'EPIgas' },
    eureka: { name: 'Eureka' },
    evernew: { name: 'Evernew' },
    exped: { name: 'EXPED' },
    feelcap: { name: 'FEELCAP' },
    fenix: { name: 'FENIX' },
    filter017: { name: 'Filter017' },
    fits: { name: 'Fits' },
    fizan: { name: 'FIZAN' },
    fjallraven: { name: 'Fjällräven' },
    flextailgear: { name: 'FLEXTAILGEAR' },
    footland: { name: 'FOOTLAND' },
    fujifilm: { name: 'Fujifilm' },
    garmin: { name: 'Garmin' },
    google: { name: 'Google' },
    gopro: { name: 'GoPro' },
    gramicci: { name: 'GRAMICCI' },
    gregory: { name: 'Gregory' },
    grivel: { name: 'Grivel' },
    gsi: { name: 'GSI' },
    haglofs: { name: 'Haglöfs' },
    hakers: { name: 'Hakers' },
    hanchor: { name: 'Hanchor' },
    hanwag: { name: 'Hanwag' },
    helinox: { name: 'Helinox' },
    hestra: { name: 'Hestra' },
    hilleberg: { name: 'Hilleberg' },
    hilltop: { name: 'Hilltop' },
    houdini: { name: 'Houdini' },
    hoverlight: { name: 'HOVERLIGHT' },
    hydrapak: { name: 'Hydrapak' },
    hydroblu: { name: 'Hydroblu' },
    hyperlite: { name: 'Hyperlite Mountain Gear' },
    icebreaker: { name: 'Icebreaker' },
    icewear: { name: 'Icewear' },
    ifyouhave: { name: 'Ifyouhave' },
    iniji: { name: 'Iniji' },
    injinji: { name: 'Injinji' },
    insta360: { name: 'Insta360' },
    isuka: { name: 'ISUKA' },
    jetboil: { name: 'Jetboil' },
    juuuni: { name: 'Juuuni' },
    k2: { name: 'K2' },
    kammok: { name: 'Kammok' },
    karbon: { name: 'Karbon' },
    karrimor: { name: 'Karrimor' },
    kask: { name: 'KASK' },
    katadyn: { name: 'Katadyn' },
    kavu: { name: 'KAVU' },
    kazmi: { name: 'KAZMI' },
    keen: { name: 'KEEN' },
    keith: { name: 'Keith' },
    kelty: { name: 'Kelty' },
    klattermusen: { name: 'Klättermusen' },
    komperdell: { name: 'Komperdell' },
    kovea: { name: 'Kovea' },
    leki: { name: 'Leki' },
    liteway: { name: 'Liteway' },
    logos: { name: 'LOGOS' },
    lowa: { name: 'LOWA' },
    luna: { name: 'Luna' },
    mammoth: { name: 'Mammoth' },
    mammut: { name: 'Mammut' },
    margarden: { name: 'MARGARDEN' },
    marmot: { name: 'Marmot' },
    matador: { name: 'Matador' },
    merrell: { name: 'Merrell' },
    milestone: { name: 'Milestone' },
    millet: { name: 'Millet' },
    minimalight: { name: 'MINIMALIGHT' },
    mld: { name: 'MLD | Mountain Laurel Designs' },
    montane: { name: 'MONTANE' },
    morakniv: { name: 'Morakniv' },
    mountainsmith: { name: 'Mountainsmith' },
    mountdoor: { name: 'MOUNTDOOR' },
    msr: { name: 'MSR | Mountain Safety Research' },
    muji: { name: 'MUJI' },
    muraco: { name: 'MURACO' },
    myog: { name: 'MYOG' },
    n9: { name: 'N9' },
    nalgene: { name: 'Nalgene' },
    nanga: { name: 'Nanga' },
    naturehike: { name: 'Naturehike' },
    nemo: { name: 'Nemo' },
    nikon: { name: 'Nikon' },
    nitecore: { name: 'NITECORE' },
    nnormal: { name: 'NNormal' },
    norrona: { name: 'Norrøna' },
    odlo: { name: 'ODLO' },
    olympus: { name: 'Olympus' },
    oofos: { name: 'OOFOS' },
    optimus: { name: 'OPTIMUS' },
    osprey: { name: 'Osprey' },
    overboard: { name: 'Overboard' },
    packtowl: { name: 'PACKTOWL' },
    pajak: { name: 'Pajak' },
    palladium: { name: 'Palladium' },
    patagonia: { name: 'Patagonia' },
    petromax: { name: 'Petromax' },
    petzl: { name: 'PETZL' },
    phenix: { name: 'Phenix' },
    platypus: { name: 'Platypus' },
    polar: { name: 'POLAR' },
    prana: { name: 'Prana' },
    primus: { name: 'Primus' },
    rab: { name: 'Rab' },
    rawlogy: { name: 'Rawlogy' },
    rawlow: { name: 'RawLow Mountain Works' },
    rei: { name: 'REI' },
    rhino: { name: 'RHINO' },
    ricoh: { name: 'RICOH' },
    ridge: { name: 'Ridge Mountain Gear' },
    rockland: { name: 'ROCKLAND' },
    salomon: { name: 'Salomon' },
    sawyer: { name: 'Sawyer' },
    scarpa: { name: 'Scarpa' },
    sealson: { name: 'SEALSON' },
    shamma: { name: 'Shamma' },
    silva: { name: 'Silva' },
    slingfin: { name: 'SlingFin' },
    smartwool: { name: 'Smartwool' },
    sony: { name: 'Sony' },
    soto: { name: 'Soto' },
    spot: { name: 'SPOT' },
    stanley: { name: 'STANLEY' },
    stasher: { name: 'Stasher' },
    staticbloom: { name: 'STATICBLOOM' },
    steripen: { name: 'Steripen' },
    suunto: { name: 'SUUNTO' },
    swd: { name: 'SWD' },
    t8: { name: 'T8' },
    takoda: { name: 'Takoda' },
    tarptent: { name: 'Tarptent' },
    teva: { name: 'Teva' },
    tierra: { name: 'Tierra' },
    tiitent: { name: 'TiiTENT' },
    timberland: { name: 'Timberland' },
    toaks: { name: 'TOAKS' },
    topeak: { name: 'Topeak' },
    topland: { name: 'Topland' },
    trailheadz: { name: 'TrailHeadz' },
    trangia: { name: 'Trangia' },
    traveller: { name: 'Traveller' },
    tyvek: { name: 'Tyvek' },
    ulsus: { name: 'Ulsus' },
    uniflame: { name: 'UNIFLAME' },
    vaga: { name: 'VÅGA' },
    valandre: { name: 'Valandre' },
    varg: { name: 'Varg' },
    vargo: { name: 'Vargo' },
    vasque: { name: 'Vasque' },
    vibram: { name: 'Vibram' },
    victorinox: { name: 'Victorinox' },
    vivobarefoot: { name: 'Vivobarefoot' },
    wildland: { name: 'Wildland' },
    wildo: { name: 'WILDO' },
    xeroshoes: { name: 'XeroShoes' },
    xiaomi: { name: 'Xiaomi' },
    xoskin: { name: 'XOSKIN' },
    yamatomichi: { name: 'Yamatomichi' },
    yamatune: { name: 'YAMAtune' },
    zamberlan: { name: 'Zamberlan' },
    zpacks: { name: 'Zpacks' },
};

const GEAR_BRAND_KEYS: string[] = Object.keys(GEAR_BRANDS).sort();

export { GEAR_BRANDS, GEAR_BRAND_KEYS };
